-- 코드를 입력하세요
SELECT fh.FLAVOR
FROM FIRST_HALF as fh
INNER JOIN ICECREAM_INFO as ic on fh.FLAVOR = ic.FLAVOR
WHERE TOTAL_ORDER > 3000 AND ic.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;

# SELECT FLAVOR
# FROM FIRST_HALF;