-- 코드를 입력하세요
SELECT B.WRITER_ID,	U.NICKNAME, SUM(B.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as B
INNER JOIN USED_GOODS_USER as U on B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;