-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as B
INNER JOIN USED_GOODS_REPLY as R on B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y') = '2022' AND DATE_FORMAT(B.CREATED_DATE, '%m') = '10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;