-- 코드를 입력하세요
SELECT I.INGREDIENT_TYPE,	sum(F.TOTAL_ORDER)
FROM FIRST_HALF as F
INNER JOIN ICECREAM_INFO as I on F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY F.TOTAL_ORDER;

# # SELECT SHIPMENT_ID,	FLAVOR,	TOTAL_ORDER
# # FROM FIRST_HALF 

# SELECT FLAVOR, INGREDIENT_TYPE
# FROM ICECREAM_INFO